# Generated by Django 3.1.1 on 2020-09-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='data',
            new_name='date',
        ),
    ]
